export enum HttpStatus {
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NO_CONTENT = 204,

    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    PAYMENT_REQUIRED = 402,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    METHOD_NOT_ALLOWED = 405,
    REQUEST_TIMEOUT = 408,
    CONFLICT = 409,
    PRECONDITION_FAILED = 412,
    UNPROCESSABLE_ENTITY = 422,
    TOO_MANY_REQUESTS = 429,

    INTERNAL_SERVER_ERROR = 500,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
}

export enum ResponseText {
    INVALID_DATA = 'Required fields are missing or invalid',
    USER_ALREADY_EXISTS = 'User already exists',
    INTERNAL_SERVER_ERROR = 'Internal server error',
    UNABLE_USER_CREATE = 'Unable to create user at the moment',
    USER_NOT_FOUND = 'User not found',
    USER_NOT_VERIFIED = 'User is not verified',
    UNABLE_TO_SEND_EMAIL = 'Unable to send email',
    UNABLE_TO_SEND_SMS = 'Unable to send SMS',
    UNABLE_TO_SAVE_VERIFICATION_CODE = 'Unable to save verification code',
    VERIFICATION_CODE_NOT_FOUND = 'Verification code not found',
    INVALID_VERIFICATION_CODE = 'Invalid verification code',
    USER_ALREADY_VERIFIED = 'User is already verified',
    USER_NOT_VERIFIED_YET = 'User is not verified yet',
    UNABLE_TO_UPDATE_USER_VERIFICATION = 'Unable to update user verification',
    UNABLE_TO_GENERATE_TOKEN = 'Unable to generate token jwt',
    INVALID_LOGIN_CREDENTIALS = 'Invalid login credentials',
    UNABLE_TO_LOGOUT = 'Unable to logout',
    UNAUTHORIZED = 'Unauthorized',
    TOKEN_EXPIRED = 'Token expired or is invalid',
    UNABLE_TO_CHANGE_PASSWORD = 'Unable to change password',
    UNABLE_TO_CREATE_DOWNLOAD = 'Unable to create download',
    DOWNLOAD_NOT_FOUND = 'Download not found',
    UNABLE_TO_DELETE_DOWNLOAD = 'Unable to delete download',
    UNABLE_TO_CLEAR_DOWNLOADS = 'Unable to clear downloads',
}
